sudo: required
services:
  - docker

before_install:
  - docker build -t nishantrauniyar/docker-react -f Dockerfile.dev .

script: 
  - docker run nishantrauniyar/docker-react npm run test -- --coverage